spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**