spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter


        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/package/**
          filters:
            - AuthenticationFilter




